package passwortmanager;


import java.awt.Button;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dominik
 */
public class Abfrage extends java.awt.Frame {

    /**
     * Creates new form Abfrage
     */
    public Abfrage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPasswordField1 = new javax.swing.JPasswordField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        gui_abfrage_btnanmelden = new java.awt.Button();

        setBackground(java.awt.Color.cyan);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 240, -1));

        label2.setText("Passwort");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, -1));

        label3.setFont(new java.awt.Font("GFS Artemisia", 3, 18)); // NOI18N
        label3.setText("Bitte Anmelden");
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        gui_abfrage_btnanmelden.setActionCommand("anmelden");
        gui_abfrage_btnanmelden.setLabel("anmelden");
        add(gui_abfrage_btnanmelden, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

private static Abfrage frame = null;
	
	public static Abfrage init()
	{
	
			try {
				if (frame == null) {
					frame = new Abfrage();
                                                        frame.gui_abfrage_btnanmelden.setActionCommand(cmbAuswahl.getGUI_Abfrage_BtnAnmelden());

				}
				else
				{
					throw new Exception("Schon eine Instance vorhanden");
				}
			} catch (Exception e) {
				e.printStackTrace();
			}
		
	return frame;
	}
	


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button gui_abfrage_btnanmelden;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField jPasswordField1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables

    public Button getGui_abfrage_btnanmelden() {
        return gui_abfrage_btnanmelden;
    }

    public void setGui_abfrage_btnanmelden(Button gui_abfrage_btnanmelden) {
        this.gui_abfrage_btnanmelden = gui_abfrage_btnanmelden;
    }

    public JPasswordField getjPasswordField1() {
        return jPasswordField1;
    }

    public void setjPasswordField1(JPasswordField jPasswordField1) {
        this.jPasswordField1 = jPasswordField1;
    }

}
