/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passwortmanager;

import java.awt.Button;
import java.awt.ScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author dominik
 */
public class Anzeigen extends java.awt.Frame {

    /**
     * Creates new form Anzeigen
     */
    public Anzeigen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gui_anzeigen_btnhinzufuegen = new java.awt.Button();
        gui_anzeigen_btn_update = new java.awt.Button();
        gui_anzeigen_scrollPane = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setBackground(java.awt.Color.orange);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gui_anzeigen_btnhinzufuegen.setActionCommand("hinzufuegen");
        gui_anzeigen_btnhinzufuegen.setLabel("hinzufuegen");
        add(gui_anzeigen_btnhinzufuegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        gui_anzeigen_btn_update.setActionCommand("update");
        gui_anzeigen_btn_update.setLabel("update");
        add(gui_anzeigen_btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, -1));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        gui_anzeigen_scrollPane.add(jScrollPane1);

        add(gui_anzeigen_scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 640, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

        
public void setTableModel(DefaultTableModel mdoel)
	{
		jTable.setModel(mdoel);
	}

	public static Anzeigen init()
	{
	
			try {
				if (frame == null) {
					frame = new Anzeigen();
                                        frame.gui_anzeigen_btn_update.setActionCommand(cmbAuswahl.getGUI_Anzeigen_BtnUpdate());
                                                frame.gui_anzeigen_btnhinzufuegen.setActionCommand(cmbAuswahl.getGUI_Anzeigen_BtnHinzufuegen());
				}
				else
				{
					throw new Exception("Schon eine Instance vorhanden");
				}
			} catch (Exception e) {
				e.printStackTrace();
			}
		
	return frame;
	}
	


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button gui_anzeigen_btn_update;
    private java.awt.Button gui_anzeigen_btnhinzufuegen;
    private java.awt.ScrollPane gui_anzeigen_scrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
private static Anzeigen frame = null;

    public Button getGui_anzeigen_btn_update() {
        return gui_anzeigen_btn_update;
    }

    public JTable getjTable() {
        return jTable;
    }

    public void setjTable(JTable jTable) {
        this.jTable = jTable;
    }

    public void setGui_anzeigen_btn_update(Button gui_anzeigen_btn_update) {
        this.gui_anzeigen_btn_update = gui_anzeigen_btn_update;
    }

    public Button getGui_anzeigen_btnhinzufuegen() {
        return gui_anzeigen_btnhinzufuegen;
    }

    public void setGui_anzeigen_btnhinzufuegen(Button gui_anzeigen_btnhinzufuegen) {
        this.gui_anzeigen_btnhinzufuegen = gui_anzeigen_btnhinzufuegen;
    }

    public ScrollPane getGui_anzeigen_scrollPane() {
        return gui_anzeigen_scrollPane;
    }

    public void setGui_anzeigen_scrollPane(ScrollPane gui_anzeigen_scrollPane) {
        this.gui_anzeigen_scrollPane = gui_anzeigen_scrollPane;
    }
}
