/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passwortmanager;

import java.awt.Button;
import java.awt.TextField;

/**
 *
 * @author dominik
 */
public class Hinzufuegen extends java.awt.Frame {

    /**
     * Creates new form Hinzufuegen
     */
    public Hinzufuegen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label3 = new java.awt.Label();
        label1 = new java.awt.Label();
        txtDienst = new java.awt.TextField();
        label2 = new java.awt.Label();
        txtwebseite = new java.awt.TextField();
        label4 = new java.awt.Label();
        txtUsername = new java.awt.TextField();
        label5 = new java.awt.Label();
        txtpasswort = new java.awt.TextField();
        txtemail = new java.awt.TextField();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        txtreseturl = new java.awt.TextField();
        label8 = new java.awt.Label();
        txtresetemail = new java.awt.TextField();
        txtfragea = new java.awt.TextField();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        txtantworta = new java.awt.TextField();
        gui_hinzufuegen_btnhinzufuegen = new java.awt.Button();
        label11 = new java.awt.Label();
        txtfrageb = new java.awt.TextField();
        label12 = new java.awt.Label();
        txtantwortb = new java.awt.TextField();
        txtkontakt = new java.awt.TextField();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        txterstellt = new java.awt.TextField();
        label15 = new java.awt.Label();
        txtgeanertam = new java.awt.TextField();

        setBackground(java.awt.Color.orange);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label3.setFont(new java.awt.Font("GFS Artemisia", 3, 18)); // NOI18N
        label3.setText("Hinzufuegen");
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        label1.setText("Dienst");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        txtDienst.setName(""); // NOI18N
        txtDienst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keine(evt);
            }
        });
        add(txtDienst, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 410, -1));

        label2.setText("Webseite");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        txtwebseite.setName(""); // NOI18N
        add(txtwebseite, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 410, 20));

        label4.setText("Username");
        add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        txtUsername.setName(""); // NOI18N
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 410, -1));

        label5.setText("Passwort");
        add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        txtpasswort.setName(""); // NOI18N
        add(txtpasswort, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 410, -1));

        txtemail.setName(""); // NOI18N
        add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 410, 20));

        label6.setText("Email");
        add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));

        label7.setText("Reset URL");
        add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        txtreseturl.setName(""); // NOI18N
        add(txtreseturl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 410, -1));

        label8.setText("Reset Email");
        add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 20));

        txtresetemail.setName(""); // NOI18N
        add(txtresetemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 410, -1));

        txtfragea.setName(""); // NOI18N
        add(txtfragea, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 410, 20));

        label9.setText("Frage_A");
        add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 20));

        label10.setText("Antwort_A");
        add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 20));

        txtantworta.setName(""); // NOI18N
        add(txtantworta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 410, -1));

        gui_hinzufuegen_btnhinzufuegen.setActionCommand("hinzufuegen");
        gui_hinzufuegen_btnhinzufuegen.setLabel("hinzufuegen");
        add(gui_hinzufuegen_btnhinzufuegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, -1, -1));

        label11.setText("Frage_B");
        add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 20));

        txtfrageb.setName(""); // NOI18N
        add(txtfrageb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 410, -1));

        label12.setText("Antwort_B");
        add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, 20));

        txtantwortb.setName(""); // NOI18N
        add(txtantwortb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 410, -1));

        txtkontakt.setName(""); // NOI18N
        add(txtkontakt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 410, 20));

        label13.setText("Kontakt");
        add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 20));

        label14.setName("txterstelltdatum"); // NOI18N
        label14.setText("Erstellt");
        add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, 20));

        txterstellt.setName(""); // NOI18N
        add(txterstellt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 410, -1));

        label15.setName("txtaenderungsdatum"); // NOI18N
        label15.setText("Geändert");
        add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, 20));

        txtgeanertam.setName(""); // NOI18N
        add(txtgeanertam, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 410, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void keine(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keine
        // TODO add your handling code here:
    }//GEN-LAST:event_keine

 private static Hinzufuegen frame = null;
	
	public static Hinzufuegen init()
	{
	
			try {
				if (frame == null) {
					frame = new Hinzufuegen();
                                        frame.gui_hinzufuegen_btnhinzufuegen.setActionCommand(cmbAuswahl.getGUI_Hinzufuegen_BtnHinzufuegen());
				}
				else
				{
					throw new Exception("Schon eine Instance vorhanden");
				}
			} catch (Exception e) {
				e.printStackTrace();
			}
		
	return frame;
	}
	



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button gui_hinzufuegen_btnhinzufuegen;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.TextField txtDienst;
    private java.awt.TextField txtUsername;
    private java.awt.TextField txtantworta;
    private java.awt.TextField txtantwortb;
    private java.awt.TextField txtemail;
    private java.awt.TextField txterstellt;
    private java.awt.TextField txtfragea;
    private java.awt.TextField txtfrageb;
    private java.awt.TextField txtgeanertam;
    private java.awt.TextField txtkontakt;
    private java.awt.TextField txtpasswort;
    private java.awt.TextField txtresetemail;
    private java.awt.TextField txtreseturl;
    private java.awt.TextField txtwebseite;
    // End of variables declaration//GEN-END:variables

    public Button getGui_hinzufuegen_btnhinzufuegen() {
        return gui_hinzufuegen_btnhinzufuegen;
    }

    public void setGui_hinzufuegen_btnhinzufuegen(Button gui_hinzufuegen_btnhinzufuegen) {
        this.gui_hinzufuegen_btnhinzufuegen = gui_hinzufuegen_btnhinzufuegen;
    }

    public TextField getTxtDienst() {
        return txtDienst;
    }

    public void setTxtDienst(TextField txtDienst) {
        this.txtDienst = txtDienst;
    }

    public TextField getTxtUsername() {
        return txtUsername;
    }

    public void setTxtUsername(TextField txtUsername) {
        this.txtUsername = txtUsername;
    }

    public TextField getTxtantworta() {
        return txtantworta;
    }

    public void setTxtantworta(TextField txtantworta) {
        this.txtantworta = txtantworta;
    }

    public TextField getTxtantwortb() {
        return txtantwortb;
    }

    public void setTxtantwortb(TextField txtantwortb) {
        this.txtantwortb = txtantwortb;
    }

    public TextField getTxtemail() {
        return txtemail;
    }

    public void setTxtemail(TextField txtemail) {
        this.txtemail = txtemail;
    }

    public TextField getTxterstellt() {
        return txterstellt;
    }

    public void setTxterstellt(TextField txterstellt) {
        this.txterstellt = txterstellt;
    }

    public TextField getTxtfragea() {
        return txtfragea;
    }

    public void setTxtfragea(TextField txtfragea) {
        this.txtfragea = txtfragea;
    }

    public TextField getTxtfrageb() {
        return txtfrageb;
    }

    public void setTxtfrageb(TextField txtfrageb) {
        this.txtfrageb = txtfrageb;
    }

    public TextField getTxtgeanertam() {
        return txtgeanertam;
    }

    public void setTxtgeanertam(TextField txtgeanertam) {
        this.txtgeanertam = txtgeanertam;
    }

    public TextField getTxtkontakt() {
        return txtkontakt;
    }

    public void setTxtkontakt(TextField txtkontakt) {
        this.txtkontakt = txtkontakt;
    }

    public TextField getTxtpasswort() {
        return txtpasswort;
    }

    public void setTxtpasswort(TextField txtpasswort) {
        this.txtpasswort = txtpasswort;
    }

    public TextField getTxtresetemail() {
        return txtresetemail;
    }

    public void setTxtresetemail(TextField txtresetemail) {
        this.txtresetemail = txtresetemail;
    }

    public TextField getTxtreseturl() {
        return txtreseturl;
    }

    public void setTxtreseturl(TextField txtreseturl) {
        this.txtreseturl = txtreseturl;
    }

    public TextField getTxtwebseite() {
        return txtwebseite;
    }

    public void setTxtwebseite(TextField txtwebseite) {
        this.txtwebseite = txtwebseite;
    }
}
